# Generated by Django 6.1 on 2026-08-14 18:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nombre Cliente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('delivery_address', models.TextField(verbose_name='Dirección de Entrega')),
                ('order_type', models.CharField(choices=[('one_time', 'Compra Única'), ('subscription', 'Suscripción Periódica')], default='one_time', max_length=20)),
                ('items_json', models.TextField(verbose_name='Detalle del Carrito (JSON)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total ($)')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('bottling', 'En Embotellado'), ('delivering', 'En Camino'), ('completed', 'Entregado')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('tagline', models.CharField(max_length=200, verbose_name='Eslogan')),
                ('category', models.CharField(choices=[('still', 'Agua de Manantial Sin Gas'), ('sparkling', 'Agua de Manantial Con Gas'), ('infused', 'Agua Enriquecida Mineral'), ('eco', 'Bidones Eco Refill')], default='still', max_length=50, verbose_name='Categoría')),
                ('volume_ml', models.IntegerField(default=750, verbose_name='Volumen (ml)')),
                ('container_type', models.CharField(default='Botella Vidrio 750ml', max_length=50, verbose_name='Envase')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($)')),
                ('ph_level', models.FloatField(default=7.8, verbose_name='Nivel pH')),
                ('tds_mg_l', models.FloatField(default=180.0, verbose_name='Residuo Seco / TDS (mg/L)')),
                ('calcium_mg_l', models.FloatField(default=45.0, verbose_name='Calcio Ca+ (mg/L)')),
                ('magnesium_mg_l', models.FloatField(default=18.0, verbose_name='Magnesio Mg+ (mg/L)')),
                ('potassium_mg_l', models.FloatField(default=4.5, verbose_name='Potasio K+ (mg/L)')),
                ('silica_mg_l', models.FloatField(default=32.0, verbose_name='Sílice SiO2 (mg/L)')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('badge', models.CharField(blank=True, max_length=50, null=True, verbose_name='Etiqueta Promocional')),
                ('icon_type', models.CharField(default='still', max_length=30, verbose_name='Tipo de Ícono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('slug', models.SlugField(unique=True)),
                ('frequency_days', models.IntegerField(default=14, verbose_name='Frecuencia (días)')),
                ('discount_percent', models.IntegerField(default=15, verbose_name='Descuento (%)')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon_name', models.CharField(default='sparkles', max_length=50)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
            },
        ),
    ]
